# Generated by Django 4.0.4 on 2022-05-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('about', models.TextField()),
            ],
        ),
    ]
