# Generated by Django 4.0.4 on 2022-05-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Setting',
        ),
    ]
