# Generated by Django 4.0.4 on 2022-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_blog_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/<django.db.models.fields.CharField>'),
        ),
    ]
